helm:
  parameters:
  - name: image.name
    value: harbor.k8s-sandbox.org/updater-test/nginx
    forcestring: true
  - name: image.tag
    value: dev@sha256:8f437832c9ce4e54989698544e138e454bcfcd4571f4fc06e31f8e3c31e24a7e
    forcestring: true
