        name: beta-ramiz-k8s-hello
        replicas: 1
        maxSurge: 1
        maxUnavailable: 1
        deployment:
          enabled: true
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/_metrics"

        PodDisruptionBudget:
          enabled: true
          maxUnavailable: 1

        HorizontalPodAutoscaler:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          averageUtilization: 70

        image:
          registry: harbor.k8s-sandbox.org
          name: k8s-hello/k8s-hello
          tag: latest
          pullPolicy: Allways

        terminationGracePeriodSeconds: 30

        securityContext:
          readOnlyRootFilesystem: false

        serviceAccount:
          name: default

        resources:
          limits:
            cpu: 100m
            memory: 56Mi
          requests:
            cpu: 100m
            memory: 56Mi
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
        maxSurge: 2
        maxUnavailable: 2

        service:
          enabled: true
          type:
            ClusterIP
          annotations:
            lido.fi/maintainer: Full name test
            prometheus.io/probe: "true"
            prometheus.io/path: /_livenessProbe
          ports:
            - name: http
              port: 8080
              targetPort: 8080
            - name: metrics
              port: 8090
              targetPort: 8090
        pvc:
          enabled: true
          storageClass: "longhorn-standard"
          accessModes:
            - ReadWriteOnce
          size: 100Mi
          mountPath: /data

        ingress:
          enabled: true
          ingressClassName: nginx-internal
          rules:
            - host: ramiz-hello.k8s-sandbox.org
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - ramiz-hello.k8s-sandbox.org
